Test/rearranging tests
PilloFoundation/duvet pull request #48
Opened 2024-06-24 01:06 UTC by PKWadsy

This PR makes several improvements on top of PR #47 regarding tests

- Reorganises tests
- Adds absolute imports
- Tests for specific error types to be thrown

2024-06-24 23:04 UTC, joshuabrownenz requested changes
Minors. 

I really like the splitting up of unit and integration. I don't know if I'm over complicating it but it would be quite cool to have seperate coverage metrics for unit and integration?

2024-06-25 04:19 UTC, merged

2024-06-25 04:29 UTC, PKWadsy commented on src/zod/models/ZodCompatibleRequest.ts
> +
Could be unknown. But I don't think it matters too much as it is never used as a concrete type anyways

2024-06-25 04:29 UTC, PKWadsy commented on src/core/endpoint-tree/EndpointTree.ts
> +
Made an issue

2024-06-25 04:29 UTC, PKWadsy commented on src/core/endpoint-builder/handlerWithValidators.ts
> +
Made an issue

2024-06-25 11:31 UTC, joshuabrownenz commented on src/zod/models/ZodCompatibleRequest.ts
> +
I meant. Should it be Zoe schema any

2024-06-25 11:32 UTC, joshuabrownenz commented on src/zod/models/ZodCompatibleRequest.ts
> +
Oh. This is the validator input with the schemas is it

2024-06-25 11:33 UTC, joshuabrownenz commented
Happy for you to merge when you are ready. I won't be available for the rest of the day to give another review